import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";

const jakarta = Plus_Jakarta_Sans({
  variable: "--font-primary",
  subsets: ["latin"],
});



export const metadata = {
  title: "CateerFit",
  // description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${jakarta.variable} h-full antialiased `}
    >
      <body className="min-h-full flex flex-col bg-background">{children}</body>
    </html>
  );
}
